scan:
  targets: "192.168.1.0/24"
  ports: "1-1024"
  interval: 300
capture:
  iface: null
  bpf_filter: null
  count: 0
anomaly:
  model_path: "models/anomaly_model.pkl"
  contamination: 0.01
database:
  url: "sqlite:///./noc_agent.db"
auth:
  oauth2_secret_key: "CHANGE_ME_SECRET"
  oauth2_algorithm: "HS256"
  access_token_expire_minutes: 60
auth_defaults:
  initial_users:
    - username: "admin"
      password: "admin123"
      roles:
        - "admin"
rbac:
  roles:
    admin:
      - "user_manage"
      - "train"
      - "infer"
      - "scan"
      - "capture"
      - "model_info"
      - "metrics"
      - "ws_packets"
    user:
      - "infer"
      - "scan"
      - "capture"
      - "metrics"